# Generated by Django 6.1 on 2026-08-30 17:38

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.ImageField(
                blank=True, null=True, upload_to=expenses.models.receipt_upload_path
            ),
        ),
    ]
