# Generated by Django 5.2.17 on 2026-08-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_expense_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
