# Generated by Django 5.2.17 on 2026-08-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_expense_ocr_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="merchant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="ocr_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="ocr_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
